print("""
Market Uygulamasına Hoşgeldiniz!
1. ÜRÜN EKLE
2. ÜRÜN SİL
3. STOK SORGULA (Ürün Adına Göre)
4. STOK SORGULA (Marka Adına Göre)
5. SUPERMARKET TOPLAM ÜRÜN STOĞU SORGULA
6. SON KULLANMA TARİHİ GEÇENLERİ KALDIR
7. SATIŞ YAP
8. İADE AL
9. GÜNLÜK TOPLAM MÜŞTERİ SAYISI
10.GÜNLÜK TOPLAM ALINAN İADE SAYISI
11.GÜNLÜK CİRO HESAPLA
12.KASAYI KAPAT""")